import { StickerItem } from '../types';

export const ALL_STICKERS: StickerItem[] = [
  // 동물 (30종)
  { id: 'stk_rabbit', name: '토끼', emoji: '🐰', category: '동물', rarity: 'normal' },
  { id: 'stk_bear', name: '곰', emoji: '🐻', category: '동물', rarity: 'normal' },
  { id: 'stk_panda', name: '판다', emoji: '🐼', category: '동물', rarity: 'special' },
  { id: 'stk_koala', name: '코알라', emoji: '🐨', category: '동물', rarity: 'normal' },
  { id: 'stk_tiger', name: '호랑이', emoji: '🐯', category: '동물', rarity: 'special' },
  { id: 'stk_lion', name: '사자', emoji: '🦁', category: '동물', rarity: 'special' },
  { id: 'stk_cat', name: '고양이', emoji: '🐱', category: '동물', rarity: 'normal' },
  { id: 'stk_dog', name: '강아지', emoji: '🐶', category: '동물', rarity: 'normal' },
  { id: 'stk_puppy', name: '멍멍이', emoji: '🐕', category: '동물', rarity: 'effort' },
  { id: 'stk_mouse', name: '생쥐', emoji: '🐭', category: '동물', rarity: 'normal' },
  { id: 'stk_hamster', name: '햄스터', emoji: '🐹', category: '동물', rarity: 'normal' },
  { id: 'stk_fox', name: '여우', emoji: '🦊', category: '동물', rarity: 'bonus' },
  { id: 'stk_monkey', name: '원숭이', emoji: '🐵', category: '동물', rarity: 'normal' },
  { id: 'stk_frog', name: '개구리', emoji: '🐸', category: '동물', rarity: 'normal' },
  { id: 'stk_penguin', name: '펭귄', emoji: '🐧', category: '동물', rarity: 'special' },
  { id: 'stk_duck', name: '오리', emoji: '🦆', category: '동물', rarity: 'normal' },
  { id: 'stk_chick', name: '병아리', emoji: '🐥', category: '동물', rarity: 'effort' },
  { id: 'stk_pig', name: '돼지', emoji: '🐷', category: '동물', rarity: 'normal' },
  { id: 'stk_cow', name: '젖소', emoji: '🐮', category: '동물', rarity: 'normal' },
  { id: 'stk_sheep', name: '양', emoji: '🐑', category: '동물', rarity: 'normal' },
  { id: 'stk_horse', name: '말', emoji: '🐴', category: '동물', rarity: 'bonus' },
  { id: 'stk_deer', name: '사슴', emoji: '🦌', category: '동물', rarity: 'bonus' },
  { id: 'stk_elephant', name: '코끼리', emoji: '🐘', category: '동물', rarity: 'special' },
  { id: 'stk_giraffe', name: '기린', emoji: '🦒', category: '동물', rarity: 'special' },
  { id: 'stk_hedgehog', name: '고슴도치', emoji: '🦔', category: '동물', rarity: 'bonus' },
  { id: 'stk_whale', name: '고래', emoji: '🐳', category: '동물', rarity: 'special' },
  { id: 'stk_dolphin', name: '돌고래', emoji: '🐬', category: '동물', rarity: 'bonus' },
  { id: 'stk_turtle', name: '거북이', emoji: '🐢', category: '동물', rarity: 'effort' },
  { id: 'stk_octopus', name: '문어', emoji: '🐙', category: '동물', rarity: 'normal' },
  { id: 'stk_crab', name: '꽃게', emoji: '🦀', category: '동물', rarity: 'normal' },

  // 과일 및 간식 (25종)
  { id: 'stk_apple', name: '사과', emoji: '🍎', category: '과일', rarity: 'normal' },
  { id: 'stk_banana', name: '바나나', emoji: '🍌', category: '과일', rarity: 'normal' },
  { id: 'stk_grape', name: '포도', emoji: '🍇', category: '과일', rarity: 'bonus' },
  { id: 'stk_strawberry', name: '딸기', emoji: '🍓', category: '과일', rarity: 'special' },
  { id: 'stk_orange', name: '오렌지', emoji: '🍊', category: '과일', rarity: 'normal' },
  { id: 'stk_peach', name: '복숭아', emoji: '🍑', category: '과일', rarity: 'bonus' },
  { id: 'stk_cherry', name: '체리', emoji: '🍒', category: '과일', rarity: 'normal' },
  { id: 'stk_watermelon', name: '수박', emoji: '🍉', category: '과일', rarity: 'bonus' },
  { id: 'stk_melon', name: '멜론', emoji: '🍈', category: '과일', rarity: 'special' },
  { id: 'stk_pineapple', name: '파인애플', emoji: '🍍', category: '과일', rarity: 'bonus' },
  { id: 'stk_kiwi', name: '키위', emoji: '🥝', category: '과일', rarity: 'normal' },
  { id: 'stk_lemon', name: '레몬', emoji: '🍋', category: '과일', rarity: 'effort' },
  { id: 'stk_carrot', name: '당근', emoji: '🥕', category: '과일', rarity: 'effort' },
  { id: 'stk_corn', name: '옥수수', emoji: '🌽', category: '과일', rarity: 'normal' },
  { id: 'stk_tomato', name: '토마토', emoji: '🍅', category: '과일', rarity: 'normal' },
  { id: 'stk_broccoli', name: '브로콜리', emoji: '🥦', category: '과일', rarity: 'effort' },
  { id: 'stk_bread', name: '식빵', emoji: '🍞', category: '과일', rarity: 'normal' },
  { id: 'stk_croissant', name: '크루아상', emoji: '🥐', category: '과일', rarity: 'bonus' },
  { id: 'stk_pancake', name: '팬케이크', emoji: '🥞', category: '과일', rarity: 'bonus' },
  { id: 'stk_icecream', name: '아이스크림', emoji: '🍦', category: '과일', rarity: 'special' },
  { id: 'stk_cookie', name: '쿠키', emoji: '🍪', category: '과일', rarity: 'normal' },
  { id: 'stk_cake', name: '딸기 케이크', emoji: '🍰', category: '과일', rarity: 'special' },
  { id: 'stk_donut', name: '도넛', emoji: '🍩', category: '과일', rarity: 'bonus' },
  { id: 'stk_candy', name: '사탕', emoji: '🍬', category: '과일', rarity: 'effort' },
  { id: 'stk_chocolate', name: '초콜릿', emoji: '🍫', category: '과일', rarity: 'normal' },

  // 우주 (15종)
  { id: 'stk_star', name: '반짝 별', emoji: '⭐', category: '우주', rarity: 'normal' },
  { id: 'stk_glowing_star', name: '황금 별', emoji: '🌟', category: '우주', rarity: 'special' },
  { id: 'stk_sparkles', name: '반짝이', emoji: '✨', category: '우주', rarity: 'effort' },
  { id: 'stk_shooting_star', name: '별똥별', emoji: '💫', category: '우주', rarity: 'special' },
  { id: 'stk_sun', name: '해님', emoji: '☀️', category: '우주', rarity: 'bonus' },
  { id: 'stk_moon', name: '달님', emoji: '🌙', category: '우주', rarity: 'bonus' },
  { id: 'stk_full_moon', name: '보름달', emoji: '🌕', category: '우주', rarity: 'normal' },
  { id: 'stk_earth', name: '지구', emoji: '🌍', category: '우주', rarity: 'special' },
  { id: 'stk_saturn', name: '고리 행성', emoji: '🪐', category: '우주', rarity: 'special' },
  { id: 'stk_rocket', name: '로켓', emoji: '🚀', category: '우주', rarity: 'special' },
  { id: 'stk_flying_saucer', name: '우주선', emoji: '🛸', category: '우주', rarity: 'special' },
  { id: 'stk_astronaut', name: '우주비행사', emoji: '🧑‍🚀', category: '우주', rarity: 'bonus' },
  { id: 'stk_alien', name: '외계인 친구', emoji: '👾', category: '우주', rarity: 'bonus' },
  { id: 'stk_rainbow', name: '무지개', emoji: '🌈', category: '우주', rarity: 'special' },
  { id: 'stk_cloud', name: '뭉게구름', emoji: '☁️', category: '우주', rarity: 'normal' },

  // 공룡 (12종)
  { id: 'stk_dino_t_rex', name: '티라노사우루스', emoji: '🦖', category: '공룡', rarity: 'special' },
  { id: 'stk_dino_sauro', name: '브라키오사우루스', emoji: '🦕', category: '공룡', rarity: 'special' },
  { id: 'stk_dino_egg', name: '공룡알', emoji: '🥚', category: '공룡', rarity: 'normal' },
  { id: 'stk_hatching_chick', name: '깨어난 아기공룡', emoji: '🐣', category: '공룡', rarity: 'effort' },
  { id: 'stk_lizard', name: '도마뱀', emoji: '🦎', category: '공룡', rarity: 'normal' },
  { id: 'stk_croc', name: '악어', emoji: '🐊', category: '공룡', rarity: 'bonus' },
  { id: 'stk_dragon', name: '아기용', emoji: '🐲', category: '공룡', rarity: 'special' },
  { id: 'stk_volcano', name: '화산', emoji: '🌋', category: '공룡', rarity: 'bonus' },
  { id: 'stk_palm', name: '야자수', emoji: '🌴', category: '공룡', rarity: 'normal' },
  { id: 'stk_fossil', name: '조개 화석', emoji: '🐚', category: '공룡', rarity: 'effort' },
  { id: 'stk_feather', name: '깃털', emoji: '🪶', category: '공룡', rarity: 'normal' },
  { id: 'stk_crystal', name: '반짝 보석', emoji: '💎', category: '공룡', rarity: 'special' },

  // 탈것과 놀이 (20종)
  { id: 'stk_car', name: '빨간 자동차', emoji: '🚗', category: '탈것', rarity: 'normal' },
  { id: 'stk_taxi', name: '노란 택시', emoji: '🚕', category: '탈것', rarity: 'normal' },
  { id: 'stk_bus', name: '붕붕 버스', emoji: '🚌', category: '탈것', rarity: 'bonus' },
  { id: 'stk_ambulance', name: '삐뽀 앰뷸런스', emoji: '🚑', category: '탈것', rarity: 'bonus' },
  { id: 'stk_fire_engine', name: '출동 소방차', emoji: '🚒', category: '탈것', rarity: 'special' },
  { id: 'stk_police_car', name: '경찰차', emoji: '🚓', category: '탈것', rarity: 'special' },
  { id: 'stk_train', name: '칙칙폭폭 기차', emoji: '🚂', category: '탈것', rarity: 'special' },
  { id: 'stk_bullet_train', name: '슝슝 고속기차', emoji: '🚄', category: '탈것', rarity: 'bonus' },
  { id: 'stk_airplane', name: '비행기', emoji: '✈️', category: '탈것', rarity: 'bonus' },
  { id: 'stk_helicopter', name: '헬리콥터', emoji: '🚁', category: '탈것', rarity: 'special' },
  { id: 'stk_sailboat', name: '돛단배', emoji: '⛵', category: '탈것', rarity: 'normal' },
  { id: 'stk_ship', name: '큰 배', emoji: '🚢', category: '탈것', rarity: 'bonus' },
  { id: 'stk_bicycle', name: '자전거', emoji: '🚲', category: '탈것', rarity: 'effort' },
  { id: 'stk_balloon_toy', name: '알록달록 풍선', emoji: '🎈', category: '탈것', rarity: 'normal' },
  { id: 'stk_pinwheel', name: '바람개비', emoji: '🪁', category: '탈것', rarity: 'effort' },
  { id: 'stk_teddy', name: '곰인형', emoji: '🧸', category: '탈것', rarity: 'special' },
  { id: 'stk_crown', name: '반짝 왕관', emoji: '👑', category: '탈것', rarity: 'special' },
  { id: 'stk_medal', name: '참 잘했어요 메달', emoji: '🏅', category: '탈것', rarity: 'effort' },
  { id: 'stk_flower', name: '예쁜 꽃', emoji: '🌸', category: '탈것', rarity: 'normal' },
  { id: 'stk_sunflower', name: '해바라기', emoji: '🌻', category: '탈것', rarity: 'bonus' },
];

export function getRandomSticker(rarity?: 'normal' | 'bonus' | 'special' | 'effort'): StickerItem {
  let pool = ALL_STICKERS;
  if (rarity) {
    pool = ALL_STICKERS.filter(s => s.rarity === rarity);
    if (pool.length === 0) pool = ALL_STICKERS;
  }
  const index = Math.floor(Math.random() * pool.length);
  return { ...pool[index], unlockedAt: new Date().toISOString() };
}
